### ISSUE TITLE
com.shobhitpuri.custombuttons.GoogleSignInButton cannot be cast to com.google.android.gms.common.SignInButton

### ISSUE THREAD

**Issue by PaulZhangIsing** [shobhitpuri/custom-google-signin-button#4]
I have followed instructions on the mainpage , imported the packages did adjustments to xml file.
Then I have do such things in my java file

 view.findViewById(R.id.sign_in_button).setOnClickListener(this);
        SignInButton signInButton = (SignInButton) view.findViewById(R.id.sign_in_button);
        signInButton.setSize(SignInButton.SIZE_STANDARD);
        signInButton.setColorScheme(SignInButton.COLOR_LIGHT);
    }

then it give me error by the time I wanna open the page contains this google login button

com.shobhitpuri.custombuttons.GoogleSignInButton cannot be cast to com.google.android.gms.common.SignInButton

**Comment by shobhitpuri** [comment]
@PaulZhangIsing Thanks for opening the issue. Can you please double check your imports, i.e if in the java file you've imported `com.google.android.gms.common.SignInButton` instead of `com.shobhitpuri.custombuttons.GoogleSignInButton` ?

**Comment by PaulZhangIsing** [comment]
Thanks I think I could close this issue. Thanks for the help!!!!!

**Comment by Julius26** [comment]
The GoogleSignInButton can't work with the default SignInButton. why is this?

**Comment by shobhitpuri** [comment]
@Julius26 Thanks for the commend. Can you please explain a bit? When you say that 'can't work', do you mean that `GoogleSignInButton` cannot be casted to `SignInButton`. This is because if you see the custom [GoogleSignInButton](https://github.com/shobhitpuri/custom-google-signin-button/blob/master/CustomGoogleSignInButton/src/main/java/com/shobhitpuri/custombuttons/GoogleSignInButton.java) implementation, its parent is `AppCompatButton` and [SignInButton](https://developers.google.com/android/reference/com/google/android/gms/common/SignInButton) parent is `FrameLayout`. If you want to case, both can be casted as `View` for the time being, since they all extend the `View` class at the end.

**Comment by rupakyeware** [comment]
Hi @shobhitpuri my app keeps crashing and I double checked all the corrections you mentioned above but it still won't work. This is the error I am getting 
Caused by: java.lang.ClassCastException: com.shobhitpuri.custombuttons.GoogleSignInButton cannot be cast to com.google.android.gms.common.SignInButton

Could you please guide me to the solution? 
Much appreaciated

**Comment by shobhitpuri** [comment]
@rupakyeware Can you see if below is the issue, else please share the stacktrace and relevant file to help debug further.

> @PaulZhangIsing Thanks for opening the issue. Can you please double check your imports on top of your `Java` file. Can you please check if by mistake you've imported `com.google.android.gms.common.SignInButton` instead of `com.shobhitpuri.custombuttons.GoogleSignInButton` ?
